// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Backs DELETE /orders/{id}. Restricted to 'pending' on purpose: once an
	// order is 'awaiting_payment' a PaymentIntent exists and the customer may
	// still pay it, so cancelling would need a refund path. Those orders are left
	// to expire instead.
	CancelPendingOrder(ctx context.Context, id int64) (Order, error)
	// One event per transaction: a poisoned payload then fails only itself
	// instead of rolling back a whole batch. SKIP LOCKED lets concurrent workers
	// (or a future second box) drain the queue without double-processing.
	//
	// The attempts cap is what stops an event that can never succeed from being
	// re-claimed every poll forever. Such rows stay unprocessed with last_error
	// set, which is the signal to go look at them.
	ClaimNextStripeEvent(ctx context.Context, maxAttempts int32) (StripeEvent, error)
	// Finalizes a reservation at checkout: moves one unit out of quantity and
	// releases the matching reservation.
	CommitStock(ctx context.Context, productID int64) (Stock, error)
	// Guarded by status = 'awaiting_payment' so a redelivered webhook can only
	// ever commit stock once for a given order. Stripe delivers at-least-once;
	// this WHERE clause is what makes that safe without a distributed lock.
	//
	// Note the guard is 'awaiting_payment', not 'pending': an order can only be
	// completed by a confirmed payment, never straight from reservation.
	CompleteOrder(ctx context.Context, id int64) (Order, error)
	// total_in_cents snapshots the product price at reserve time so a later price
	// change can't move the amount charged. expires_at bounds how long the
	// reservation may hold stock.
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error)
	// The sweeper's claim-and-mark. Driven by our own clock and our own table,
	// deliberately independent of Stripe: if Stripe never calls back, stock must
	// still come back on sale.
	//
	// FOR UPDATE SKIP LOCKED makes this safe to run from more than one process —
	// a second sweeper skips rows already claimed rather than blocking on them.
	// The caller must ReleaseStock for every returned row in this same
	// transaction, so an order can never be marked expired without its unit
	// being returned.
	ExpireOrders(ctx context.Context, limit int32) ([]Order, error)
	// The payment_intent.payment_failed path. Guarded so a redelivered failure
	// releases stock at most once.
	FailOrder(ctx context.Context, id int64) (Order, error)
	// Joins the owning customer's identity so callers can check ownership without
	// a second round trip. cognito_sub is preferred over email for that check;
	// it is NULL only for customers who predate the column.
	FindOrderByID(ctx context.Context, id int64) (FindOrderByIDRow, error)
	// The Stripe webhook's only handle back to an order.
	FindOrderByPaymentIntentID(ctx context.Context, stripePaymentIntentID pgtype.Text) (FindOrderByPaymentIntentIDRow, error)
	FindProductByID(ctx context.Context, id int64) (FindProductByIDRow, error)
	// The entry point for both delivery paths — the webhook handler and the event
	// poller. id is Stripe's own evt_... identifier, so ON CONFLICT DO NOTHING
	// turns at-least-once delivery into exactly-once processing, and makes it safe
	// to run both paths at the same time or to re-scan an overlapping window.
	// Returns 0 rows when the event was already recorded, which callers log as a
	// duplicate rather than an error.
	InsertStripeEvent(ctx context.Context, arg InsertStripeEventParams) (int64, error)
	// The poller's resume point, in Stripe's clock.
	//
	// Reading it from the table on every tick rather than holding it in memory is
	// what makes the poller crash-safe and stateless: after a restart, a deploy,
	// or an outage of any length it resumes from the last event actually stored.
	// Returns NULL when nothing has been recorded yet, which the caller turns into
	// a bounded initial lookback so a fresh box doesn't replay all of history.
	LatestStripeEventCreatedAt(ctx context.Context) (pgtype.Timestamptz, error)
	// Bridges a Cognito identity to a customers row, and backfills cognito_sub on
	// rows created before that column existed.
	//
	// Still upserts on email (the pre-existing unique constraint) so no data
	// migration is needed. COALESCE keeps the first sub ever recorded rather than
	// letting a later caller overwrite it. This is the expand phase: once every
	// row has a sub, the conflict target can flip to cognito_sub, which closes
	// the hole that email is mutable in Cognito and sub is not.
	LinkCustomer(ctx context.Context, arg LinkCustomerParams) (Customer, error)
	// Backs GET /orders. Joins the product name so a list view doesn't need N+1
	// follow-up requests.
	ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]ListOrdersByCustomerRow, error)
	// Sold-out products sort last; everything else sorts by start_at (already-started
	// sales first, soonest-upcoming next). Among sold-out products, the one that
	// started most recently sorts last, standing in for "most recently ended last"
	// since there's no explicit end time.
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	// Checkout's half: records the PaymentIntent and hands the order to Stripe.
	// Guarded on 'pending' so two concurrent checkouts can't attach two intents
	// to one order — the loser sees no rows and is rejected.
	MarkOrderAwaitingPayment(ctx context.Context, arg MarkOrderAwaitingPaymentParams) (Order, error)
	// Leaves processed_at NULL so the event is retried on the next poll.
	MarkStripeEventFailed(ctx context.Context, arg MarkStripeEventFailedParams) error
	// last_error is NULL for a clean success. It is set — with processed_at still
	// stamped — for an event that can never succeed no matter how often it is
	// retried, such as a payment that arrived for an order the sweeper already
	// expired. Retrying those forever would spin the worker; leaving the message
	// behind is what makes them findable.
	MarkStripeEventProcessed(ctx context.Context, arg MarkStripeEventProcessedParams) error
	// The other way a reservation ends: cancelled, payment failed, or expired.
	// Puts the unit back on sale without touching quantity. Guarded on
	// num_reserved > 0 so a double release can't drive the counter negative.
	//
	// Always call this in the same transaction as the orders-table guard that
	// authorized it (CancelPendingOrder / FailOrder / ExpireOrders). That guard
	// is what makes the release happen at most once per order; this WHERE clause
	// is only the backstop.
	ReleaseStock(ctx context.Context, productID int64) (Stock, error)
	// Atomic check-and-increment: only succeeds while quantity - num_reserved > 0,
	// so concurrent callers can never over-reserve a product's stock.
	//
	// This statement is the project's core correctness claim. Deliberately left
	// untouched by the payment/expiry work so the contention strategy stays
	// swappable (Redis counters, advisory locks, SERIALIZABLE) after profiling.
	ReserveStock(ctx context.Context, productID int64) (Stock, error)
}

var _ Querier = (*Queries)(nil)
