#!/usr/bin/env bash
# Builds the storefront for filming at http://localhost:8080.
#
# That address matters: it is the production topology exactly — one Go binary
# serving the compiled React bundle from a single origin, with no CORS and no
# separate dev server. The only thing production has that this does not is TLS.
#
# It also happens to be the only way to demonstrate signing in. Cognito refuses
# to register a callback URL that is not HTTPS, with one exemption for the
# loopback hosts, so http://localhost:8080/auth/callback is registered and the
# deployed box's address can never be.
#
# Your existing web/.env is left untouched. Vite loads .env first and then
# .env.<mode>, so the demo values here override the dev ones for this build
# only, and `npm run dev` keeps working as before.
set -euo pipefail

cd "$(dirname "$0")/../../web"

if [ ! -f .env ]; then
	echo "web/.env is missing — copy web/.env.example and fill it in first" >&2
	exit 1
fi

# Carry over the values that identify the Cognito pool and the Stripe account,
# then override the three that decide where the app thinks it is running.
{
	echo "# Generated by scripts/demo/build-frontend.sh. Edits will be overwritten."
	grep -E '^VITE_(COGNITO_DOMAIN|COGNITO_CLIENT_ID|STRIPE_PUBLISHABLE_KEY)=' .env

	# Empty means same origin: the API is served by the same process on the
	# same port, so there is no cross-origin request to configure.
	echo "VITE_API_BASE_URL="

	# Set explicitly rather than left empty. The code falls back to the current
	# origin only when this is absent; an empty string is a value, and would
	# produce a redirect to nowhere.
	echo "VITE_COGNITO_REDIRECT_URI=http://localhost:8080/auth/callback"

	# The paste-a-token shortcut is for driving the app before Hosted UI
	# exists. Off here: the demo signs in for real.
	echo "VITE_ENABLE_DEV_TOKEN_LOGIN=false"
} > .env.demo

npx vite build --mode demo

echo
echo "Built web/dist for http://localhost:8080"
echo "Start the API with: make server"
